- hosts: localhost
  tasks:
          - add_host:
                  name: "{{ hostvars.task14.docker_networksettings.IPAddress }}"
                  ansible_ssh_user: "root"
                  ansible_ssh_pass: "docker"
                  groups: "container"

- hosts: container
  tasks:
          - name: "Install httpd"
            package:
                    name: "httpd"
                    state: present
          - name: "Deploy WebPage"
            copy:
                    content: "My Task 14.2 is completed. This page is comming from {{ ansible_facts.default_ipv4.address }} </br>"
                    dest: "/var/www/html/index.html"
          - name: "start httpd service"
            command: "/usr/sbin/httpd"
